### ISSUE TITLE
ImportError: cannot import name XmlImport

### ISSUE THREAD

**Issue by b-cornu** [DuChemin/MEIMassaging#15]
Hi,

I've some trouble with the command below :
```
python massage_mei.py test.mei --out result.mei
```
The result : 
```
Traceback (most recent call last):
  File "massage_mei.py", line 4, in <module>
    from analyze.analyze import analyze as make_analysis
  File "/Users/Ben/Downloads/MEIMassaging-master/massage/analyze/analyze.py", line 4, in <module>
    from pymei import XmlImport
ImportError: cannot import name XmlImport
```

i've install all required package (even libmei with the link : https://github.com/DDMAL/libmei/wiki/Compiling-and-Installing)
I'm on MacOS 10.10.

Thx

**Comment by ahankinson** [comment]
If you've installed the latest version of libmei, there is a change in how import/export works. The `XmlImport` class no longer exists, and has been replaced by two top-level functions.

An example of its use can be seen in the Python Unit Tests:

https://github.com/DDMAL/libmei/blob/master/python/test/xmlimport_test.py#L4

So you should be able to change the code to something like

```
from pymei import documentFromFile

res = documentFromFile('myfile.mei')
MEI_doc = res.getMeiDocument()
```

`XmlExport` has also changed to functions. You can also find examples of its use in:

https://github.com/DDMAL/libmei/blob/master/python/test/xmlexport_test.py

Let me know if you need any more assistance.

**Comment by b-cornu** [comment]
Thank you @ahankinson, it works like a charm !
